### ISSUE TITLE
how to handle async data?

### ISSUE THREAD

**Issue by deezahyn** [yoshuawuyts/barracks#27]
Is there an example for this?

**Comment by yoshuawuyts** [comment]
I guess if you're not familiar with node's [`events`](https://iojs.org/api/events.html) it isn't straight forward. `barracks` is asynchronous by design. 

```js
// require barracks
const b = require('barracks')

// when 'beep' echo 'boop'
b.on('beep', () => console.log('boop'))

// wait 1 second, then call with value 'beep',
// triggering 'boop'
setTimeout(b.bind(null, 'beep'), 1000)
```

As dispalyed in the example: calling `b('beep')` can be done in response to any async event. Does this asnwer your question?

**Comment by deezahyn** [comment]
ohh, now I get it it so like pub-sub?

**Comment by yoshuawuyts** [comment]
Yup, exactly! Took me a while to realize that a router is actually a one-to-many relationship and an EventEmitter is the perfect data abstraction for that.

**Comment by deezahyn** [comment]
thank you!, closing this, will experiment on this.
