### ISSUE TITLE
noSubscriptions: true -> subscriptions: false ?

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/barracks#40]
I feel like I read somewhere that having negative params like the former is less readable/obvious than the latter (no + true = false). Just a suggestion as you're finalizing the API. Don't mean to cause more trouble!

**Comment by yoshuawuyts** [comment]
hmmm, no I think you're right, doing `store.start({ subscriptions: false })` seems like a better API haha - I'm quite sure I had a reason for it but I'm tired right now so I'll revisit tomorrow - def thanks for raising it tho! :sparkles:
