### ISSUE TITLE
Tips for namespace name

### ISSUE THREAD

**Issue by kwoon** [yoshuawuyts/barracks#51]
When i try to give namespace name something like ```"pages:home"``` i catch error. I guess problem in [this fragment](https://github.com/yoshuawuyts/barracks/blob/master/index.js#L153). Perhaps it would be correct, when action would be the last part of ```actionName```?

**Comment by yoshuawuyts** [comment]
yeah, try and make namespaces single words, as when calling send they'll be prefixed already. e.g.
- namespace: 'user`
- action: `logout`
- `send('user:logout')`

does that make sense? Cheers!

**Comment by kwoon** [comment]
Maybe you are right. Lets make all more simply! :)
