### ISSUE TITLE
State and previous state are equal if a namespace is used

### ISSUE THREAD

**Issue by fapian** [yoshuawuyts/barracks#56]
Hey,

i prepared this bin (http://requirebin.com/?gist=27d3737a054e1e044080d04bf516a493) to showcase the bug.

If you run it, the previous state of the namespaced version is equal to the new state.
If i do the same without a namespace everything works as i would expect it.

**Comment by yoshuawuyts** [comment]
Ah yeah, damn - that's not good. Investigating

**Comment by yoshuawuyts** [comment]
Found the bug, we were mutating the previous state rather than overriding it
